/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 74a727d4f89ad27e7ade0d7b844e85f5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		chat: DurableObjectNamespace<import("./src/server").Chat>;
	}
}
interface Env extends Cloudflare.Env {}
