/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: ad26484074651155ea1a13fea62a20b7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		AI: Ai;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
	}
}
interface Env extends Cloudflare.Env {}
